// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProTracker.Data;

#nullable disable

namespace ProTracker.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260702123243_AddScheduledSessions")]
    partial class AddScheduledSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProTracker.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ProTracker.Models.AssessmentPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("AssessmentPeriods");
                });

            modelBuilder.Entity("ProTracker.Models.CoachTeamScope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoachId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("CoachId", "TeamId")
                        .IsUnique();

                    b.ToTable("CoachTeamScopes");
                });

            modelBuilder.Entity("ProTracker.Models.DailyMealPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DailyCalories")
                        .HasColumnType("integer");

                    b.Property<int>("DailyCarbs")
                        .HasColumnType("integer");

                    b.Property<int>("DailyFats")
                        .HasColumnType("integer");

                    b.Property<int>("DailyProtein")
                        .HasColumnType("integer");

                    b.Property<string>("DayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<int>("WeeklyNutritionPlanId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyNutritionPlanId");

                    b.ToTable("DailyMealPlans");
                });

            modelBuilder.Entity("ProTracker.Models.FoodAlternativesLibrary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlternativeFood")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CalorieMatchScore")
                        .HasColumnType("integer");

                    b.Property<int?>("Calories")
                        .HasColumnType("integer");

                    b.Property<int>("CarbMatchScore")
                        .HasColumnType("integer");

                    b.Property<int?>("Carbs")
                        .HasColumnType("integer");

                    b.Property<int>("FatMatchScore")
                        .HasColumnType("integer");

                    b.Property<int?>("Fats")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalFood")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Protein")
                        .HasColumnType("integer");

                    b.Property<int>("ProteinMatchScore")
                        .HasColumnType("integer");

                    b.Property<string>("ReasonExplanation")
                        .HasColumnType("text");

                    b.Property<int>("RecoveryValue")
                        .HasColumnType("integer");

                    b.Property<string>("SportPerformanceNote")
                        .HasColumnType("text");

                    b.Property<string>("SuggestedPortion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FoodAlternativesLibrary");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlternativeFood = "Greek yogurt",
                            CalorieMatchScore = 3,
                            Calories = 130,
                            CarbMatchScore = 3,
                            Carbs = 8,
                            FatMatchScore = 3,
                            Fats = 4,
                            OriginalFood = "Eggs",
                            Protein = 15,
                            ProteinMatchScore = 4,
                            ReasonExplanation = "High in protein with probiotics; comparable protein density to eggs per serving.",
                            RecoveryValue = 4,
                            SportPerformanceNote = "Good post-training protein source, easy to digest.",
                            SuggestedPortion = "150g"
                        },
                        new
                        {
                            Id = 2,
                            AlternativeFood = "Tofu",
                            CalorieMatchScore = 3,
                            Calories = 120,
                            CarbMatchScore = 2,
                            Carbs = 3,
                            FatMatchScore = 3,
                            Fats = 6,
                            OriginalFood = "Eggs",
                            Protein = 15,
                            ProteinMatchScore = 4,
                            ReasonExplanation = "Complete plant protein; firm tofu has a similar protein-per-gram profile to eggs.",
                            RecoveryValue = 3,
                            SportPerformanceNote = "Suitable pre- or post-session, low fat load.",
                            SuggestedPortion = "150g"
                        },
                        new
                        {
                            Id = 3,
                            AlternativeFood = "Cottage cheese",
                            CalorieMatchScore = 3,
                            Calories = 130,
                            CarbMatchScore = 2,
                            Carbs = 5,
                            FatMatchScore = 2,
                            Fats = 4,
                            OriginalFood = "Eggs",
                            Protein = 17,
                            ProteinMatchScore = 5,
                            ReasonExplanation = "Very high protein-to-calorie ratio, close match to eggs for muscle repair.",
                            RecoveryValue = 4,
                            SportPerformanceNote = "Slow-digesting casein protein, good before bed for recovery.",
                            SuggestedPortion = "150g"
                        },
                        new
                        {
                            Id = 4,
                            AlternativeFood = "Chicken breast",
                            CalorieMatchScore = 3,
                            Calories = 165,
                            CarbMatchScore = 1,
                            Carbs = 0,
                            FatMatchScore = 2,
                            Fats = 4,
                            OriginalFood = "Eggs",
                            Protein = 31,
                            ProteinMatchScore = 5,
                            ReasonExplanation = "Higher protein density than eggs, minimal carbs, lean if skinless.",
                            RecoveryValue = 4,
                            SportPerformanceNote = "Solid lean protein for muscle maintenance across training cycles.",
                            SuggestedPortion = "100g"
                        },
                        new
                        {
                            Id = 5,
                            AlternativeFood = "Tuna",
                            CalorieMatchScore = 2,
                            Calories = 116,
                            CarbMatchScore = 1,
                            Carbs = 0,
                            FatMatchScore = 2,
                            Fats = 1,
                            OriginalFood = "Eggs",
                            Protein = 25,
                            ProteinMatchScore = 5,
                            ReasonExplanation = "High protein, low calorie alternative with added anti-inflammatory fats.",
                            RecoveryValue = 4,
                            SportPerformanceNote = "Lean protein plus omega-3s, useful for recovery days.",
                            SuggestedPortion = "100g"
                        },
                        new
                        {
                            Id = 6,
                            AlternativeFood = "Lentils",
                            CalorieMatchScore = 3,
                            Calories = 230,
                            CarbMatchScore = 4,
                            Carbs = 40,
                            FatMatchScore = 1,
                            Fats = 1,
                            OriginalFood = "Eggs",
                            Protein = 18,
                            ProteinMatchScore = 3,
                            ReasonExplanation = "Lower protein density than eggs but pairs protein with fiber and carbs.",
                            RecoveryValue = 3,
                            SportPerformanceNote = "Adds slow-release carbs alongside protein for endurance athletes.",
                            SuggestedPortion = "200g cooked"
                        },
                        new
                        {
                            Id = 7,
                            AlternativeFood = "Soy milk",
                            CalorieMatchScore = 3,
                            Calories = 80,
                            CarbMatchScore = 3,
                            Carbs = 4,
                            FatMatchScore = 3,
                            Fats = 4,
                            OriginalFood = "Milk / Dairy",
                            Protein = 7,
                            ProteinMatchScore = 4,
                            ReasonExplanation = "Soy milk has the closest protein content to dairy milk among plant milks.",
                            RecoveryValue = 3,
                            SportPerformanceNote = "Closest plant-based match for post-workout shakes.",
                            SuggestedPortion = "240ml"
                        },
                        new
                        {
                            Id = 8,
                            AlternativeFood = "Lactose-free milk",
                            CalorieMatchScore = 4,
                            Calories = 150,
                            CarbMatchScore = 4,
                            Carbs = 12,
                            FatMatchScore = 4,
                            Fats = 8,
                            OriginalFood = "Milk / Dairy",
                            Protein = 8,
                            ProteinMatchScore = 5,
                            ReasonExplanation = "Same nutrition profile as regular milk, lactose enzymatically broken down.",
                            RecoveryValue = 4,
                            SportPerformanceNote = "Direct nutritional swap, no performance trade-off.",
                            SuggestedPortion = "240ml"
                        },
                        new
                        {
                            Id = 9,
                            AlternativeFood = "Almond milk with protein",
                            CalorieMatchScore = 2,
                            Calories = 60,
                            CarbMatchScore = 2,
                            Carbs = 2,
                            FatMatchScore = 2,
                            Fats = 2,
                            OriginalFood = "Milk / Dairy",
                            Protein = 5,
                            ProteinMatchScore = 3,
                            ReasonExplanation = "Plain almond milk is protein-poor, so a protein-fortified version is needed to approach dairy milk.",
                            RecoveryValue = 2,
                            SportPerformanceNote = "Lower calorie option; pair with another protein source on training days.",
                            SuggestedPortion = "240ml"
                        },
                        new
                        {
                            Id = 10,
                            AlternativeFood = "Salmon",
                            CalorieMatchScore = 3,
                            Calories = 200,
                            CarbMatchScore = 1,
                            Carbs = 0,
                            FatMatchScore = 2,
                            Fats = 11,
                            OriginalFood = "Chicken",
                            Protein = 25,
                            ProteinMatchScore = 5,
                            ReasonExplanation = "Comparable lean protein with added anti-inflammatory benefits.",
                            RecoveryValue = 5,
                            SportPerformanceNote = "Excellent recovery food due to omega-3 content.",
                            SuggestedPortion = "120g"
                        },
                        new
                        {
                            Id = 11,
                            AlternativeFood = "Turkey breast",
                            CalorieMatchScore = 3,
                            Calories = 165,
                            CarbMatchScore = 1,
                            Carbs = 0,
                            FatMatchScore = 2,
                            Fats = 3,
                            OriginalFood = "Chicken",
                            Protein = 31,
                            ProteinMatchScore = 5,
                            ReasonExplanation = "Almost identical macro profile to chicken breast.",
                            RecoveryValue = 4,
                            SportPerformanceNote = "Near-identical swap for any chicken-based meal plan.",
                            SuggestedPortion = "100g"
                        },
                        new
                        {
                            Id = 12,
                            AlternativeFood = "Firm tofu",
                            CalorieMatchScore = 3,
                            Calories = 120,
                            CarbMatchScore = 2,
                            Carbs = 3,
                            FatMatchScore = 3,
                            Fats = 6,
                            OriginalFood = "Chicken",
                            Protein = 15,
                            ProteinMatchScore = 4,
                            ReasonExplanation = "Lower protein density than chicken but complete amino acid profile.",
                            RecoveryValue = 3,
                            SportPerformanceNote = "Good vegetarian/vegan substitute in stir-fries and bowls.",
                            SuggestedPortion = "150g"
                        },
                        new
                        {
                            Id = 13,
                            AlternativeFood = "Red lentils",
                            CalorieMatchScore = 3,
                            Calories = 230,
                            CarbMatchScore = 4,
                            Carbs = 40,
                            FatMatchScore = 1,
                            Fats = 1,
                            OriginalFood = "Chicken",
                            Protein = 18,
                            ProteinMatchScore = 3,
                            ReasonExplanation = "Lower protein density than chicken, higher carb and fiber content.",
                            RecoveryValue = 3,
                            SportPerformanceNote = "Adds carbs for endurance sessions instead of pure protein.",
                            SuggestedPortion = "200g cooked"
                        },
                        new
                        {
                            Id = 14,
                            AlternativeFood = "Black beans",
                            CalorieMatchScore = 3,
                            Calories = 220,
                            CarbMatchScore = 4,
                            Carbs = 40,
                            FatMatchScore = 1,
                            Fats = 1,
                            OriginalFood = "Chicken",
                            Protein = 15,
                            ProteinMatchScore = 3,
                            ReasonExplanation = "Moderate protein with added carbohydrate and fiber not present in chicken.",
                            RecoveryValue = 3,
                            SportPerformanceNote = "Budget-friendly plant protein with good fiber for general health.",
                            SuggestedPortion = "200g cooked"
                        },
                        new
                        {
                            Id = 15,
                            AlternativeFood = "Potatoes",
                            CalorieMatchScore = 3,
                            Calories = 160,
                            CarbMatchScore = 4,
                            Carbs = 37,
                            FatMatchScore = 1,
                            Fats = 0,
                            OriginalFood = "Rice",
                            Protein = 4,
                            ProteinMatchScore = 1,
                            ReasonExplanation = "Comparable carbohydrate load to rice with more potassium.",
                            RecoveryValue = 4,
                            SportPerformanceNote = "High-glycemic carb source, effective for fast glycogen refill post-match.",
                            SuggestedPortion = "200g"
                        },
                        new
                        {
                            Id = 16,
                            AlternativeFood = "Pasta",
                            CalorieMatchScore = 4,
                            Calories = 220,
                            CarbMatchScore = 5,
                            Carbs = 43,
                            FatMatchScore = 1,
                            Fats = 1,
                            OriginalFood = "Rice",
                            Protein = 8,
                            ProteinMatchScore = 2,
                            ReasonExplanation = "Very close carbohydrate density to rice, slightly more protein.",
                            RecoveryValue = 4,
                            SportPerformanceNote = "Classic pre-match carb-loading option.",
                            SuggestedPortion = "180g cooked"
                        },
                        new
                        {
                            Id = 17,
                            AlternativeFood = "Quinoa",
                            CalorieMatchScore = 3,
                            Calories = 220,
                            CarbMatchScore = 4,
                            Carbs = 39,
                            FatMatchScore = 2,
                            Fats = 4,
                            OriginalFood = "Rice",
                            Protein = 8,
                            ProteinMatchScore = 3,
                            ReasonExplanation = "Similar carb content to rice with meaningfully more protein.",
                            RecoveryValue = 4,
                            SportPerformanceNote = "Adds complete protein on top of carb intake, useful for plant-based athletes.",
                            SuggestedPortion = "180g cooked"
                        },
                        new
                        {
                            Id = 18,
                            AlternativeFood = "Oats",
                            CalorieMatchScore = 3,
                            Calories = 300,
                            CarbMatchScore = 4,
                            Carbs = 54,
                            FatMatchScore = 2,
                            Fats = 5,
                            OriginalFood = "Rice",
                            Protein = 10,
                            ProteinMatchScore = 3,
                            ReasonExplanation = "Comparable carbohydrate density with more fiber and protein than rice.",
                            RecoveryValue = 4,
                            SportPerformanceNote = "Good slow-release carb option for pre-training meals.",
                            SuggestedPortion = "80g dry"
                        },
                        new
                        {
                            Id = 19,
                            AlternativeFood = "Tahini",
                            CalorieMatchScore = 4,
                            Calories = 180,
                            CarbMatchScore = 2,
                            Carbs = 6,
                            FatMatchScore = 4,
                            Fats = 16,
                            OriginalFood = "Peanut butter",
                            Protein = 5,
                            ProteinMatchScore = 3,
                            ReasonExplanation = "Sesame-based, similar calorie-dense fat profile to peanut butter without nuts.",
                            RecoveryValue = 3,
                            SportPerformanceNote = "Good fat/calorie source for athletes needing peanut-free spreads.",
                            SuggestedPortion = "30g"
                        },
                        new
                        {
                            Id = 20,
                            AlternativeFood = "Almond butter",
                            CalorieMatchScore = 4,
                            Calories = 190,
                            CarbMatchScore = 2,
                            Carbs = 6,
                            FatMatchScore = 4,
                            Fats = 17,
                            OriginalFood = "Peanut butter",
                            Protein = 7,
                            ProteinMatchScore = 3,
                            ReasonExplanation = "Very close macro profile to peanut butter (note: still a tree nut, not suitable for peanut+tree nut allergies).",
                            RecoveryValue = 3,
                            SportPerformanceNote = "Comparable energy-dense snack for endurance athletes.",
                            SuggestedPortion = "30g"
                        },
                        new
                        {
                            Id = 21,
                            AlternativeFood = "Sunflower seed butter",
                            CalorieMatchScore = 4,
                            Calories = 185,
                            CarbMatchScore = 2,
                            Carbs = 6,
                            FatMatchScore = 4,
                            Fats = 16,
                            OriginalFood = "Peanut butter",
                            Protein = 6,
                            ProteinMatchScore = 3,
                            ReasonExplanation = "Nut-free spread with a close calorie and fat profile to peanut butter.",
                            RecoveryValue = 3,
                            SportPerformanceNote = "Safe nut-free, seed-based alternative for school/team settings.",
                            SuggestedPortion = "30g"
                        });
                });

            modelBuilder.Entity("ProTracker.Models.ImprovementPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoachNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAIGenerated")
                        .HasColumnType("boolean");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("PositionFocus")
                        .HasColumnType("text");

                    b.Property<string>("SkillTargets")
                        .HasColumnType("text");

                    b.Property<string>("SportSpecificDrills")
                        .HasColumnType("text");

                    b.Property<string>("TrainingRecommendations")
                        .HasColumnType("text");

                    b.Property<string>("WeeklyGoals")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("ImprovementPlans");
                });

            modelBuilder.Entity("ProTracker.Models.InjuryRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyPart")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpectedReturnDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InjuryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InjuryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RecoveredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecoveryStatus")
                        .HasColumnType("integer");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("TreatmentPlan")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("InjuryRecords");
                });

            modelBuilder.Entity("ProTracker.Models.MatchPerformance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Opponent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PerformanceRating")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("SportSpecificStats")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("MatchPerformances");
                });

            modelBuilder.Entity("ProTracker.Models.MatchResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<string>("Competition")
                        .HasColumnType("text");

                    b.Property<int>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<bool>("IsHome")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OpponentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Venue")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("MatchResults");
                });

            modelBuilder.Entity("ProTracker.Models.NutritionGuidance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Disclaimer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FoodsToLimit")
                        .HasColumnType("text");

                    b.Property<string>("FoodsToPrioritize")
                        .HasColumnType("text");

                    b.Property<string>("Goal")
                        .HasColumnType("text");

                    b.Property<string>("HydrationTips")
                        .HasColumnType("text");

                    b.Property<bool>("IsAIGenerated")
                        .HasColumnType("boolean");

                    b.Property<string>("MealPlanJson")
                        .HasColumnType("text");

                    b.Property<string>("MealSuggestions")
                        .HasColumnType("text");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("RecoveryTips")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("NutritionGuidances");
                });

            modelBuilder.Entity("ProTracker.Models.PlannedMeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DailyMealPlanId")
                        .HasColumnType("integer");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DailyMealPlanId");

                    b.ToTable("PlannedMeals");
                });

            modelBuilder.Entity("ProTracker.Models.PlannedMealItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("integer");

                    b.Property<int>("Carbs")
                        .HasColumnType("integer");

                    b.Property<int>("Fats")
                        .HasColumnType("integer");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSwapped")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalFoodName")
                        .HasColumnType("text");

                    b.Property<int>("PlannedMealId")
                        .HasColumnType("integer");

                    b.Property<string>("Portion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Protein")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlannedMealId");

                    b.ToTable("PlannedMealItems");
                });

            modelBuilder.Entity("ProTracker.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("CoachNotes")
                        .HasColumnType("text");

                    b.Property<int>("FitnessLevel")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Goals")
                        .HasColumnType("text");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<string>("InjuryNotes")
                        .HasColumnType("text");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("SportId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("SportId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ProTracker.Models.PlayerAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentPeriodId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentPeriodId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerAssessments");
                });

            modelBuilder.Entity("ProTracker.Models.PlayerMatchRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<int>("Goals")
                        .HasColumnType("integer");

                    b.Property<int>("MatchResultId")
                        .HasColumnType("integer");

                    b.Property<int>("MinutesPlayed")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,1)");

                    b.Property<int>("RedCards")
                        .HasColumnType("integer");

                    b.Property<int>("YellowCards")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchResultId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerMatchRatings");
                });

            modelBuilder.Entity("ProTracker.Models.PlayerNutritionProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("PreferenceType")
                        .HasColumnType("integer");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("SpecificItem")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerNutritionProfiles");
                });

            modelBuilder.Entity("ProTracker.Models.PlayerStatScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerAssessmentId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(3,1)");

                    b.Property<int>("SportStatCategoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerAssessmentId");

                    b.HasIndex("SportStatCategoryId");

                    b.ToTable("PlayerStatScores");
                });

            modelBuilder.Entity("ProTracker.Models.PlayerTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("CoachId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletedNote")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerTasks");
                });

            modelBuilder.Entity("ProTracker.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SportId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SportId");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Goalkeeper",
                            SportId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Defender",
                            SportId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Midfielder",
                            SportId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Winger",
                            SportId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Striker",
                            SportId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Point Guard",
                            SportId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Shooting Guard",
                            SportId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "Small Forward",
                            SportId = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "Power Forward",
                            SportId = 2
                        },
                        new
                        {
                            Id = 10,
                            Name = "Center",
                            SportId = 2
                        },
                        new
                        {
                            Id = 11,
                            Name = "Setter",
                            SportId = 3
                        },
                        new
                        {
                            Id = 12,
                            Name = "Outside Hitter",
                            SportId = 3
                        },
                        new
                        {
                            Id = 13,
                            Name = "Opposite Hitter",
                            SportId = 3
                        },
                        new
                        {
                            Id = 14,
                            Name = "Middle Blocker",
                            SportId = 3
                        },
                        new
                        {
                            Id = 15,
                            Name = "Libero",
                            SportId = 3
                        },
                        new
                        {
                            Id = 16,
                            Name = "Defender",
                            SportId = 4
                        },
                        new
                        {
                            Id = 17,
                            Name = "Blocker",
                            SportId = 4
                        },
                        new
                        {
                            Id = 18,
                            Name = "All-Round Player",
                            SportId = 4
                        },
                        new
                        {
                            Id = 19,
                            Name = "Singles Player",
                            SportId = 5
                        },
                        new
                        {
                            Id = 20,
                            Name = "Doubles Player",
                            SportId = 5
                        },
                        new
                        {
                            Id = 21,
                            Name = "Baseline Player",
                            SportId = 5
                        },
                        new
                        {
                            Id = 22,
                            Name = "Serve-and-Volley Player",
                            SportId = 5
                        },
                        new
                        {
                            Id = 23,
                            Name = "All-Court Player",
                            SportId = 5
                        });
                });

            modelBuilder.Entity("ProTracker.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ProTracker.Models.ScheduledSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Focus")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("SessionType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "StartTime");

                    b.ToTable("ScheduledSessions");
                });

            modelBuilder.Entity("ProTracker.Models.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IconOrImage")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Eleven-a-side football.",
                            Name = "Football / Soccer"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Five-a-side basketball.",
                            Name = "Basketball"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Six-a-side indoor volleyball.",
                            Name = "Volleyball Indoor"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Two-a-side beach volleyball.",
                            Name = "Beach Volleyball"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Singles or doubles tennis.",
                            Name = "Tennis"
                        });
                });

            modelBuilder.Entity("ProTracker.Models.SportStatCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SportId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SportId");

                    b.ToTable("SportStatCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Speed",
                            SportId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Stamina",
                            SportId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Passing",
                            SportId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shooting",
                            SportId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Defense",
                            SportId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ball Control",
                            SportId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Agility",
                            SportId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Match Performance",
                            SportId = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "Shooting",
                            SportId = 2
                        },
                        new
                        {
                            Id = 10,
                            Name = "Dribbling",
                            SportId = 2
                        },
                        new
                        {
                            Id = 11,
                            Name = "Passing",
                            SportId = 2
                        },
                        new
                        {
                            Id = 12,
                            Name = "Defense",
                            SportId = 2
                        },
                        new
                        {
                            Id = 13,
                            Name = "Rebounding",
                            SportId = 2
                        },
                        new
                        {
                            Id = 14,
                            Name = "Vertical Jump",
                            SportId = 2
                        },
                        new
                        {
                            Id = 15,
                            Name = "Court Vision",
                            SportId = 2
                        },
                        new
                        {
                            Id = 16,
                            Name = "Stamina",
                            SportId = 2
                        },
                        new
                        {
                            Id = 17,
                            Name = "Serving",
                            SportId = 3
                        },
                        new
                        {
                            Id = 18,
                            Name = "Passing",
                            SportId = 3
                        },
                        new
                        {
                            Id = 19,
                            Name = "Setting",
                            SportId = 3
                        },
                        new
                        {
                            Id = 20,
                            Name = "Blocking",
                            SportId = 3
                        },
                        new
                        {
                            Id = 21,
                            Name = "Spiking",
                            SportId = 3
                        },
                        new
                        {
                            Id = 22,
                            Name = "Reaction",
                            SportId = 3
                        },
                        new
                        {
                            Id = 23,
                            Name = "Jumping",
                            SportId = 3
                        },
                        new
                        {
                            Id = 24,
                            Name = "Team Communication",
                            SportId = 3
                        },
                        new
                        {
                            Id = 25,
                            Name = "Serving",
                            SportId = 4
                        },
                        new
                        {
                            Id = 26,
                            Name = "Passing",
                            SportId = 4
                        },
                        new
                        {
                            Id = 27,
                            Name = "Spiking",
                            SportId = 4
                        },
                        new
                        {
                            Id = 28,
                            Name = "Defense",
                            SportId = 4
                        },
                        new
                        {
                            Id = 29,
                            Name = "Movement on Sand",
                            SportId = 4
                        },
                        new
                        {
                            Id = 30,
                            Name = "Stamina",
                            SportId = 4
                        },
                        new
                        {
                            Id = 31,
                            Name = "Reaction",
                            SportId = 4
                        },
                        new
                        {
                            Id = 32,
                            Name = "Communication",
                            SportId = 4
                        },
                        new
                        {
                            Id = 33,
                            Name = "Serve",
                            SportId = 5
                        },
                        new
                        {
                            Id = 34,
                            Name = "Forehand",
                            SportId = 5
                        },
                        new
                        {
                            Id = 35,
                            Name = "Backhand",
                            SportId = 5
                        },
                        new
                        {
                            Id = 36,
                            Name = "Footwork",
                            SportId = 5
                        },
                        new
                        {
                            Id = 37,
                            Name = "Stamina",
                            SportId = 5
                        },
                        new
                        {
                            Id = 38,
                            Name = "Match Consistency",
                            SportId = 5
                        },
                        new
                        {
                            Id = 39,
                            Name = "Return",
                            SportId = 5
                        },
                        new
                        {
                            Id = 40,
                            Name = "Mental Focus",
                            SportId = 5
                        });
                });

            modelBuilder.Entity("ProTracker.Models.TaskItem", b =>
                {
                    b.Property<int>("TaskItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaskItemId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrainingPlanId")
                        .HasColumnType("integer");

                    b.HasKey("TaskItemId");

                    b.HasIndex("TrainingPlanId");

                    b.ToTable("TaskItems");
                });

            modelBuilder.Entity("ProTracker.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoachId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SportId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("SportId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("ProTracker.Models.TrainingPlan", b =>
                {
                    b.Property<int>("TrainingPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrainingPlanId"));

                    b.Property<string>("AthleteId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoachId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Goal")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TrainingPlanId");

                    b.ToTable("TrainingPlans");
                });

            modelBuilder.Entity("ProTracker.Models.TrainingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendanceStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("ProTracker.Models.WeeklyNutritionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAIGenerated")
                        .HasColumnType("boolean");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("WeekStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("WeeklyNutritionPlans");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ProTracker.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ProTracker.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProTracker.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ProTracker.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProTracker.Models.AssessmentPeriod", b =>
                {
                    b.HasOne("ProTracker.Models.Team", "Team")
                        .WithMany("AssessmentPeriods")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ProTracker.Models.CoachTeamScope", b =>
                {
                    b.HasOne("ProTracker.Models.Team", "Team")
                        .WithMany("CoachScopes")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ProTracker.Models.DailyMealPlan", b =>
                {
                    b.HasOne("ProTracker.Models.WeeklyNutritionPlan", "WeeklyNutritionPlan")
                        .WithMany("DailyMealPlans")
                        .HasForeignKey("WeeklyNutritionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeeklyNutritionPlan");
                });

            modelBuilder.Entity("ProTracker.Models.ImprovementPlan", b =>
                {
                    b.HasOne("ProTracker.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ProTracker.Models.InjuryRecord", b =>
                {
                    b.HasOne("ProTracker.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ProTracker.Models.MatchPerformance", b =>
                {
                    b.HasOne("ProTracker.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ProTracker.Models.MatchResult", b =>
                {
                    b.HasOne("ProTracker.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ProTracker.Models.NutritionGuidance", b =>
                {
                    b.HasOne("ProTracker.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ProTracker.Models.PlannedMeal", b =>
                {
                    b.HasOne("ProTracker.Models.DailyMealPlan", "DailyMealPlan")
                        .WithMany("PlannedMeals")
                        .HasForeignKey("DailyMealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyMealPlan");
                });

            modelBuilder.Entity("ProTracker.Models.PlannedMealItem", b =>
                {
                    b.HasOne("ProTracker.Models.PlannedMeal", "PlannedMeal")
                        .WithMany("PlannedMealItems")
                        .HasForeignKey("PlannedMealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlannedMeal");
                });

            modelBuilder.Entity("ProTracker.Models.Player", b =>
                {
                    b.HasOne("ProTracker.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProTracker.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProTracker.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("Sport");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ProTracker.Models.PlayerAssessment", b =>
                {
                    b.HasOne("ProTracker.Models.AssessmentPeriod", "AssessmentPeriod")
                        .WithMany("PlayerAssessments")
                        .HasForeignKey("AssessmentPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProTracker.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentPeriod");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ProTracker.Models.PlayerMatchRating", b =>
                {
                    b.HasOne("ProTracker.Models.MatchResult", "MatchResult")
                        .WithMany("Ratings")
                        .HasForeignKey("MatchResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProTracker.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchResult");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ProTracker.Models.PlayerNutritionProfile", b =>
                {
                    b.HasOne("ProTracker.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ProTracker.Models.PlayerStatScore", b =>
                {
                    b.HasOne("ProTracker.Models.PlayerAssessment", "PlayerAssessment")
                        .WithMany("StatScores")
                        .HasForeignKey("PlayerAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProTracker.Models.SportStatCategory", "SportStatCategory")
                        .WithMany()
                        .HasForeignKey("SportStatCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlayerAssessment");

                    b.Navigation("SportStatCategory");
                });

            modelBuilder.Entity("ProTracker.Models.PlayerTask", b =>
                {
                    b.HasOne("ProTracker.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ProTracker.Models.Position", b =>
                {
                    b.HasOne("ProTracker.Models.Sport", "Sport")
                        .WithMany("Positions")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("ProTracker.Models.ScheduledSession", b =>
                {
                    b.HasOne("ProTracker.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ProTracker.Models.SportStatCategory", b =>
                {
                    b.HasOne("ProTracker.Models.Sport", "Sport")
                        .WithMany("StatCategories")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("ProTracker.Models.TaskItem", b =>
                {
                    b.HasOne("ProTracker.Models.TrainingPlan", "TrainingPlan")
                        .WithMany("Tasks")
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("ProTracker.Models.Team", b =>
                {
                    b.HasOne("ProTracker.Models.Sport", "Sport")
                        .WithMany("Teams")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("ProTracker.Models.TrainingSession", b =>
                {
                    b.HasOne("ProTracker.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProTracker.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ProTracker.Models.WeeklyNutritionPlan", b =>
                {
                    b.HasOne("ProTracker.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ProTracker.Models.AssessmentPeriod", b =>
                {
                    b.Navigation("PlayerAssessments");
                });

            modelBuilder.Entity("ProTracker.Models.DailyMealPlan", b =>
                {
                    b.Navigation("PlannedMeals");
                });

            modelBuilder.Entity("ProTracker.Models.MatchResult", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("ProTracker.Models.PlannedMeal", b =>
                {
                    b.Navigation("PlannedMealItems");
                });

            modelBuilder.Entity("ProTracker.Models.PlayerAssessment", b =>
                {
                    b.Navigation("StatScores");
                });

            modelBuilder.Entity("ProTracker.Models.Sport", b =>
                {
                    b.Navigation("Positions");

                    b.Navigation("StatCategories");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("ProTracker.Models.Team", b =>
                {
                    b.Navigation("AssessmentPeriods");

                    b.Navigation("CoachScopes");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("ProTracker.Models.TrainingPlan", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("ProTracker.Models.WeeklyNutritionPlan", b =>
                {
                    b.Navigation("DailyMealPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
