// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProTracker.Data;

#nullable disable

namespace ProTracker.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260624191027_AddRefreshTokens")]
    partial class AddRefreshTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProTracker.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ProTracker.Models.AssessmentPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("AssessmentPeriods");
                });

            modelBuilder.Entity("ProTracker.Models.CoachTeamScope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoachId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("CoachId", "TeamId")
                        .IsUnique();

                    b.ToTable("CoachTeamScopes");
                });

            modelBuilder.Entity("ProTracker.Models.FoodAlternativesLibrary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlternativeFood")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CalorieMatchScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarbMatchScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FatMatchScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFood")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProteinMatchScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReasonExplanation")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecoveryValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SportPerformanceNote")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FoodAlternativesLibrary");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlternativeFood = "Greek yogurt",
                            CalorieMatchScore = 3,
                            CarbMatchScore = 3,
                            FatMatchScore = 3,
                            OriginalFood = "Eggs",
                            ProteinMatchScore = 4,
                            ReasonExplanation = "High in protein with probiotics; comparable protein density to eggs per serving.",
                            RecoveryValue = 4,
                            SportPerformanceNote = "Good post-training protein source, easy to digest."
                        },
                        new
                        {
                            Id = 2,
                            AlternativeFood = "Tofu",
                            CalorieMatchScore = 3,
                            CarbMatchScore = 2,
                            FatMatchScore = 3,
                            OriginalFood = "Eggs",
                            ProteinMatchScore = 4,
                            ReasonExplanation = "Complete plant protein; firm tofu has a similar protein-per-gram profile to eggs.",
                            RecoveryValue = 3,
                            SportPerformanceNote = "Suitable pre- or post-session, low fat load."
                        },
                        new
                        {
                            Id = 3,
                            AlternativeFood = "Cottage cheese",
                            CalorieMatchScore = 3,
                            CarbMatchScore = 2,
                            FatMatchScore = 2,
                            OriginalFood = "Eggs",
                            ProteinMatchScore = 5,
                            ReasonExplanation = "Very high protein-to-calorie ratio, close match to eggs for muscle repair.",
                            RecoveryValue = 4,
                            SportPerformanceNote = "Slow-digesting casein protein, good before bed for recovery."
                        },
                        new
                        {
                            Id = 4,
                            AlternativeFood = "Chicken",
                            CalorieMatchScore = 3,
                            CarbMatchScore = 1,
                            FatMatchScore = 2,
                            OriginalFood = "Eggs",
                            ProteinMatchScore = 5,
                            ReasonExplanation = "Higher protein density than eggs, minimal carbs, lean if skinless.",
                            RecoveryValue = 4,
                            SportPerformanceNote = "Solid lean protein for muscle maintenance across training cycles."
                        },
                        new
                        {
                            Id = 5,
                            AlternativeFood = "Tuna",
                            CalorieMatchScore = 2,
                            CarbMatchScore = 1,
                            FatMatchScore = 2,
                            OriginalFood = "Eggs",
                            ProteinMatchScore = 5,
                            ReasonExplanation = "High protein, low calorie alternative with added anti-inflammatory fats.",
                            RecoveryValue = 4,
                            SportPerformanceNote = "Lean protein plus omega-3s, useful for recovery days."
                        },
                        new
                        {
                            Id = 6,
                            AlternativeFood = "Lentils",
                            CalorieMatchScore = 3,
                            CarbMatchScore = 4,
                            FatMatchScore = 1,
                            OriginalFood = "Eggs",
                            ProteinMatchScore = 3,
                            ReasonExplanation = "Lower protein density than eggs but pairs protein with fiber and carbs.",
                            RecoveryValue = 3,
                            SportPerformanceNote = "Adds slow-release carbs alongside protein for endurance athletes."
                        },
                        new
                        {
                            Id = 7,
                            AlternativeFood = "Soy milk",
                            CalorieMatchScore = 3,
                            CarbMatchScore = 3,
                            FatMatchScore = 3,
                            OriginalFood = "Milk / Dairy",
                            ProteinMatchScore = 4,
                            ReasonExplanation = "Soy milk has the closest protein content to dairy milk among plant milks.",
                            RecoveryValue = 3,
                            SportPerformanceNote = "Closest plant-based match for post-workout shakes."
                        },
                        new
                        {
                            Id = 8,
                            AlternativeFood = "Lactose-free milk",
                            CalorieMatchScore = 4,
                            CarbMatchScore = 4,
                            FatMatchScore = 4,
                            OriginalFood = "Milk / Dairy",
                            ProteinMatchScore = 5,
                            ReasonExplanation = "Same nutrition profile as regular milk, lactose enzymatically broken down.",
                            RecoveryValue = 4,
                            SportPerformanceNote = "Direct nutritional swap, no performance trade-off."
                        },
                        new
                        {
                            Id = 9,
                            AlternativeFood = "Almond milk with added protein",
                            CalorieMatchScore = 2,
                            CarbMatchScore = 2,
                            FatMatchScore = 2,
                            OriginalFood = "Milk / Dairy",
                            ProteinMatchScore = 3,
                            ReasonExplanation = "Plain almond milk is protein-poor, so a protein-fortified version is needed to approach dairy milk.",
                            RecoveryValue = 2,
                            SportPerformanceNote = "Lower calorie option; pair with another protein source on training days."
                        },
                        new
                        {
                            Id = 10,
                            AlternativeFood = "Fish",
                            CalorieMatchScore = 3,
                            CarbMatchScore = 1,
                            FatMatchScore = 2,
                            OriginalFood = "Chicken",
                            ProteinMatchScore = 5,
                            ReasonExplanation = "Comparable lean protein with added anti-inflammatory benefits.",
                            RecoveryValue = 5,
                            SportPerformanceNote = "Excellent recovery food due to omega-3 content."
                        },
                        new
                        {
                            Id = 11,
                            AlternativeFood = "Turkey",
                            CalorieMatchScore = 3,
                            CarbMatchScore = 1,
                            FatMatchScore = 2,
                            OriginalFood = "Chicken",
                            ProteinMatchScore = 5,
                            ReasonExplanation = "Almost identical macro profile to chicken breast.",
                            RecoveryValue = 4,
                            SportPerformanceNote = "Near-identical swap for any chicken-based meal plan."
                        },
                        new
                        {
                            Id = 12,
                            AlternativeFood = "Tofu",
                            CalorieMatchScore = 3,
                            CarbMatchScore = 2,
                            FatMatchScore = 3,
                            OriginalFood = "Chicken",
                            ProteinMatchScore = 4,
                            ReasonExplanation = "Lower protein density than chicken but complete amino acid profile.",
                            RecoveryValue = 3,
                            SportPerformanceNote = "Good vegetarian/vegan substitute in stir-fries and bowls."
                        },
                        new
                        {
                            Id = 13,
                            AlternativeFood = "Lentils",
                            CalorieMatchScore = 3,
                            CarbMatchScore = 4,
                            FatMatchScore = 1,
                            OriginalFood = "Chicken",
                            ProteinMatchScore = 3,
                            ReasonExplanation = "Lower protein density than chicken, higher carb and fiber content.",
                            RecoveryValue = 3,
                            SportPerformanceNote = "Adds carbs for endurance sessions instead of pure protein."
                        },
                        new
                        {
                            Id = 14,
                            AlternativeFood = "Beans",
                            CalorieMatchScore = 3,
                            CarbMatchScore = 4,
                            FatMatchScore = 1,
                            OriginalFood = "Chicken",
                            ProteinMatchScore = 3,
                            ReasonExplanation = "Moderate protein with added carbohydrate and fiber not present in chicken.",
                            RecoveryValue = 3,
                            SportPerformanceNote = "Budget-friendly plant protein with good fiber for general health."
                        },
                        new
                        {
                            Id = 15,
                            AlternativeFood = "Potatoes",
                            CalorieMatchScore = 3,
                            CarbMatchScore = 4,
                            FatMatchScore = 1,
                            OriginalFood = "Rice",
                            ProteinMatchScore = 1,
                            ReasonExplanation = "Comparable carbohydrate load to rice with more potassium.",
                            RecoveryValue = 4,
                            SportPerformanceNote = "High-glycemic carb source, effective for fast glycogen refill post-match."
                        },
                        new
                        {
                            Id = 16,
                            AlternativeFood = "Pasta",
                            CalorieMatchScore = 4,
                            CarbMatchScore = 5,
                            FatMatchScore = 1,
                            OriginalFood = "Rice",
                            ProteinMatchScore = 2,
                            ReasonExplanation = "Very close carbohydrate density to rice, slightly more protein.",
                            RecoveryValue = 4,
                            SportPerformanceNote = "Classic pre-match carb-loading option."
                        },
                        new
                        {
                            Id = 17,
                            AlternativeFood = "Quinoa",
                            CalorieMatchScore = 3,
                            CarbMatchScore = 4,
                            FatMatchScore = 2,
                            OriginalFood = "Rice",
                            ProteinMatchScore = 3,
                            ReasonExplanation = "Similar carb content to rice with meaningfully more protein.",
                            RecoveryValue = 4,
                            SportPerformanceNote = "Adds complete protein on top of carb intake, useful for plant-based athletes."
                        },
                        new
                        {
                            Id = 18,
                            AlternativeFood = "Oats",
                            CalorieMatchScore = 3,
                            CarbMatchScore = 4,
                            FatMatchScore = 2,
                            OriginalFood = "Rice",
                            ProteinMatchScore = 3,
                            ReasonExplanation = "Comparable carbohydrate density with more fiber and protein than rice.",
                            RecoveryValue = 4,
                            SportPerformanceNote = "Good slow-release carb option for pre-training meals."
                        },
                        new
                        {
                            Id = 19,
                            AlternativeFood = "Tahini",
                            CalorieMatchScore = 4,
                            CarbMatchScore = 2,
                            FatMatchScore = 4,
                            OriginalFood = "Peanut butter",
                            ProteinMatchScore = 3,
                            ReasonExplanation = "Sesame-based, similar calorie-dense fat profile to peanut butter without nuts.",
                            RecoveryValue = 3,
                            SportPerformanceNote = "Good fat/calorie source for athletes needing peanut-free spreads."
                        },
                        new
                        {
                            Id = 20,
                            AlternativeFood = "Almond butter",
                            CalorieMatchScore = 4,
                            CarbMatchScore = 2,
                            FatMatchScore = 4,
                            OriginalFood = "Peanut butter",
                            ProteinMatchScore = 3,
                            ReasonExplanation = "Very close macro profile to peanut butter (note: still a tree nut, not suitable for peanut+tree nut allergies).",
                            RecoveryValue = 3,
                            SportPerformanceNote = "Comparable energy-dense snack for endurance athletes."
                        },
                        new
                        {
                            Id = 21,
                            AlternativeFood = "Sunflower seed butter",
                            CalorieMatchScore = 4,
                            CarbMatchScore = 2,
                            FatMatchScore = 4,
                            OriginalFood = "Peanut butter",
                            ProteinMatchScore = 3,
                            ReasonExplanation = "Nut-free spread with a close calorie and fat profile to peanut butter.",
                            RecoveryValue = 3,
                            SportPerformanceNote = "Safe nut-free, seed-based alternative for school/team settings."
                        });
                });

            modelBuilder.Entity("ProTracker.Models.ImprovementPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoachNotes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAIGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PositionFocus")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillTargets")
                        .HasColumnType("TEXT");

                    b.Property<string>("SportSpecificDrills")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrainingRecommendations")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeeklyGoals")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("ImprovementPlans");
                });

            modelBuilder.Entity("ProTracker.Models.InjuryRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpectedReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InjuryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InjuryType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecoveryStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("InjuryRecords");
                });

            modelBuilder.Entity("ProTracker.Models.MatchPerformance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Opponent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PerformanceRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SportSpecificStats")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("MatchPerformances");
                });

            modelBuilder.Entity("ProTracker.Models.NutritionGuidance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Disclaimer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FoodsToLimit")
                        .HasColumnType("TEXT");

                    b.Property<string>("FoodsToPrioritize")
                        .HasColumnType("TEXT");

                    b.Property<string>("Goal")
                        .HasColumnType("TEXT");

                    b.Property<string>("HydrationTips")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAIGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MealSuggestions")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecoveryTips")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("NutritionGuidances");
                });

            modelBuilder.Entity("ProTracker.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoachNotes")
                        .HasColumnType("TEXT");

                    b.Property<int>("FitnessLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Goals")
                        .HasColumnType("TEXT");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<string>("InjuryNotes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("SportId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("SportId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ProTracker.Models.PlayerAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssessmentPeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentPeriodId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerAssessments");
                });

            modelBuilder.Entity("ProTracker.Models.PlayerNutritionProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreferenceType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecificItem")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerNutritionProfiles");
                });

            modelBuilder.Entity("ProTracker.Models.PlayerStatScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerAssessmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SportStatCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerAssessmentId");

                    b.HasIndex("SportStatCategoryId");

                    b.ToTable("PlayerStatScores");
                });

            modelBuilder.Entity("ProTracker.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SportId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SportId");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Goalkeeper",
                            SportId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Defender",
                            SportId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Midfielder",
                            SportId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Winger",
                            SportId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Striker",
                            SportId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Point Guard",
                            SportId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Shooting Guard",
                            SportId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "Small Forward",
                            SportId = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "Power Forward",
                            SportId = 2
                        },
                        new
                        {
                            Id = 10,
                            Name = "Center",
                            SportId = 2
                        },
                        new
                        {
                            Id = 11,
                            Name = "Setter",
                            SportId = 3
                        },
                        new
                        {
                            Id = 12,
                            Name = "Outside Hitter",
                            SportId = 3
                        },
                        new
                        {
                            Id = 13,
                            Name = "Opposite Hitter",
                            SportId = 3
                        },
                        new
                        {
                            Id = 14,
                            Name = "Middle Blocker",
                            SportId = 3
                        },
                        new
                        {
                            Id = 15,
                            Name = "Libero",
                            SportId = 3
                        },
                        new
                        {
                            Id = 16,
                            Name = "Defender",
                            SportId = 4
                        },
                        new
                        {
                            Id = 17,
                            Name = "Blocker",
                            SportId = 4
                        },
                        new
                        {
                            Id = 18,
                            Name = "All-Round Player",
                            SportId = 4
                        },
                        new
                        {
                            Id = 19,
                            Name = "Singles Player",
                            SportId = 5
                        },
                        new
                        {
                            Id = 20,
                            Name = "Doubles Player",
                            SportId = 5
                        },
                        new
                        {
                            Id = 21,
                            Name = "Baseline Player",
                            SportId = 5
                        },
                        new
                        {
                            Id = 22,
                            Name = "Serve-and-Volley Player",
                            SportId = 5
                        },
                        new
                        {
                            Id = 23,
                            Name = "All-Court Player",
                            SportId = 5
                        });
                });

            modelBuilder.Entity("ProTracker.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ProTracker.Models.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconOrImage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Eleven-a-side football.",
                            Name = "Football / Soccer"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Five-a-side basketball.",
                            Name = "Basketball"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Six-a-side indoor volleyball.",
                            Name = "Volleyball Indoor"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Two-a-side beach volleyball.",
                            Name = "Beach Volleyball"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Singles or doubles tennis.",
                            Name = "Tennis"
                        });
                });

            modelBuilder.Entity("ProTracker.Models.SportStatCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SportId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SportId");

                    b.ToTable("SportStatCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Speed",
                            SportId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Stamina",
                            SportId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Passing",
                            SportId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shooting",
                            SportId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Defense",
                            SportId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ball Control",
                            SportId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Agility",
                            SportId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Match Performance",
                            SportId = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "Shooting",
                            SportId = 2
                        },
                        new
                        {
                            Id = 10,
                            Name = "Dribbling",
                            SportId = 2
                        },
                        new
                        {
                            Id = 11,
                            Name = "Passing",
                            SportId = 2
                        },
                        new
                        {
                            Id = 12,
                            Name = "Defense",
                            SportId = 2
                        },
                        new
                        {
                            Id = 13,
                            Name = "Rebounding",
                            SportId = 2
                        },
                        new
                        {
                            Id = 14,
                            Name = "Vertical Jump",
                            SportId = 2
                        },
                        new
                        {
                            Id = 15,
                            Name = "Court Vision",
                            SportId = 2
                        },
                        new
                        {
                            Id = 16,
                            Name = "Stamina",
                            SportId = 2
                        },
                        new
                        {
                            Id = 17,
                            Name = "Serving",
                            SportId = 3
                        },
                        new
                        {
                            Id = 18,
                            Name = "Passing",
                            SportId = 3
                        },
                        new
                        {
                            Id = 19,
                            Name = "Setting",
                            SportId = 3
                        },
                        new
                        {
                            Id = 20,
                            Name = "Blocking",
                            SportId = 3
                        },
                        new
                        {
                            Id = 21,
                            Name = "Spiking",
                            SportId = 3
                        },
                        new
                        {
                            Id = 22,
                            Name = "Reaction",
                            SportId = 3
                        },
                        new
                        {
                            Id = 23,
                            Name = "Jumping",
                            SportId = 3
                        },
                        new
                        {
                            Id = 24,
                            Name = "Team Communication",
                            SportId = 3
                        },
                        new
                        {
                            Id = 25,
                            Name = "Serving",
                            SportId = 4
                        },
                        new
                        {
                            Id = 26,
                            Name = "Passing",
                            SportId = 4
                        },
                        new
                        {
                            Id = 27,
                            Name = "Spiking",
                            SportId = 4
                        },
                        new
                        {
                            Id = 28,
                            Name = "Defense",
                            SportId = 4
                        },
                        new
                        {
                            Id = 29,
                            Name = "Movement on Sand",
                            SportId = 4
                        },
                        new
                        {
                            Id = 30,
                            Name = "Stamina",
                            SportId = 4
                        },
                        new
                        {
                            Id = 31,
                            Name = "Reaction",
                            SportId = 4
                        },
                        new
                        {
                            Id = 32,
                            Name = "Communication",
                            SportId = 4
                        },
                        new
                        {
                            Id = 33,
                            Name = "Serve",
                            SportId = 5
                        },
                        new
                        {
                            Id = 34,
                            Name = "Forehand",
                            SportId = 5
                        },
                        new
                        {
                            Id = 35,
                            Name = "Backhand",
                            SportId = 5
                        },
                        new
                        {
                            Id = 36,
                            Name = "Footwork",
                            SportId = 5
                        },
                        new
                        {
                            Id = 37,
                            Name = "Stamina",
                            SportId = 5
                        },
                        new
                        {
                            Id = 38,
                            Name = "Match Consistency",
                            SportId = 5
                        },
                        new
                        {
                            Id = 39,
                            Name = "Return",
                            SportId = 5
                        },
                        new
                        {
                            Id = 40,
                            Name = "Mental Focus",
                            SportId = 5
                        });
                });

            modelBuilder.Entity("ProTracker.Models.TaskItem", b =>
                {
                    b.Property<int>("TaskItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrainingPlanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskItemId");

                    b.HasIndex("TrainingPlanId");

                    b.ToTable("TaskItems");
                });

            modelBuilder.Entity("ProTracker.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoachId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SportId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("SportId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("ProTracker.Models.TrainingPlan", b =>
                {
                    b.Property<int>("TrainingPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AthleteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoachId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Goal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TrainingPlanId");

                    b.ToTable("TrainingPlans");
                });

            modelBuilder.Entity("ProTracker.Models.TrainingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttendanceStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ProTracker.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ProTracker.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProTracker.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ProTracker.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProTracker.Models.AssessmentPeriod", b =>
                {
                    b.HasOne("ProTracker.Models.Team", "Team")
                        .WithMany("AssessmentPeriods")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ProTracker.Models.CoachTeamScope", b =>
                {
                    b.HasOne("ProTracker.Models.Team", "Team")
                        .WithMany("CoachScopes")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ProTracker.Models.ImprovementPlan", b =>
                {
                    b.HasOne("ProTracker.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ProTracker.Models.InjuryRecord", b =>
                {
                    b.HasOne("ProTracker.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ProTracker.Models.MatchPerformance", b =>
                {
                    b.HasOne("ProTracker.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ProTracker.Models.NutritionGuidance", b =>
                {
                    b.HasOne("ProTracker.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ProTracker.Models.Player", b =>
                {
                    b.HasOne("ProTracker.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProTracker.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProTracker.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("Sport");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ProTracker.Models.PlayerAssessment", b =>
                {
                    b.HasOne("ProTracker.Models.AssessmentPeriod", "AssessmentPeriod")
                        .WithMany("PlayerAssessments")
                        .HasForeignKey("AssessmentPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProTracker.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentPeriod");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ProTracker.Models.PlayerNutritionProfile", b =>
                {
                    b.HasOne("ProTracker.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ProTracker.Models.PlayerStatScore", b =>
                {
                    b.HasOne("ProTracker.Models.PlayerAssessment", "PlayerAssessment")
                        .WithMany("StatScores")
                        .HasForeignKey("PlayerAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProTracker.Models.SportStatCategory", "SportStatCategory")
                        .WithMany()
                        .HasForeignKey("SportStatCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlayerAssessment");

                    b.Navigation("SportStatCategory");
                });

            modelBuilder.Entity("ProTracker.Models.Position", b =>
                {
                    b.HasOne("ProTracker.Models.Sport", "Sport")
                        .WithMany("Positions")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("ProTracker.Models.SportStatCategory", b =>
                {
                    b.HasOne("ProTracker.Models.Sport", "Sport")
                        .WithMany("StatCategories")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("ProTracker.Models.TaskItem", b =>
                {
                    b.HasOne("ProTracker.Models.TrainingPlan", "TrainingPlan")
                        .WithMany("Tasks")
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("ProTracker.Models.Team", b =>
                {
                    b.HasOne("ProTracker.Models.Sport", "Sport")
                        .WithMany("Teams")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("ProTracker.Models.TrainingSession", b =>
                {
                    b.HasOne("ProTracker.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProTracker.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ProTracker.Models.AssessmentPeriod", b =>
                {
                    b.Navigation("PlayerAssessments");
                });

            modelBuilder.Entity("ProTracker.Models.PlayerAssessment", b =>
                {
                    b.Navigation("StatScores");
                });

            modelBuilder.Entity("ProTracker.Models.Sport", b =>
                {
                    b.Navigation("Positions");

                    b.Navigation("StatCategories");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("ProTracker.Models.Team", b =>
                {
                    b.Navigation("AssessmentPeriods");

                    b.Navigation("CoachScopes");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("ProTracker.Models.TrainingPlan", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
