import { Document, Page, View, Text, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { paddingTop: 40, paddingBottom: 48, paddingHorizontal: 42, fontSize: 10, fontFamily: 'Helvetica', color: '#1f2937' },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', borderBottomWidth: 2, borderBottomColor: '#111827', paddingBottom: 8, marginBottom: 16 },
  brand: { fontSize: 18, fontFamily: 'Helvetica-Bold', color: '#111827' },
  brandSub: { fontSize: 9, color: '#6b7280', marginTop: 2 },
  meta: { fontSize: 10, color: '#4b5563', textAlign: 'right' },
  sectionTitle: { fontSize: 11, fontFamily: 'Helvetica-Bold', color: '#111827', textTransform: 'uppercase', letterSpacing: 0.6, marginBottom: 6, marginTop: 14 },
  testBlock: { borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 4, padding: 8, marginBottom: 8 },
  testName: { fontSize: 11, fontFamily: 'Helvetica-Bold', color: '#111827', marginBottom: 3 },
  label: { fontSize: 8, fontFamily: 'Helvetica-Bold', color: '#6b7280', textTransform: 'uppercase', marginTop: 4 },
  body: { fontSize: 9, color: '#374151', lineHeight: 1.35 },
  tableHead: { flexDirection: 'row', backgroundColor: '#f3f4f6', borderWidth: 1, borderColor: '#d1d5db' },
  tableRow: { flexDirection: 'row', borderLeftWidth: 1, borderRightWidth: 1, borderBottomWidth: 1, borderColor: '#d1d5db', minHeight: 22 },
  nameCell: { width: '28%', padding: 5, fontSize: 9, fontFamily: 'Helvetica-Bold', borderRightWidth: 1, borderColor: '#d1d5db' },
  th: { padding: 5, fontSize: 8, fontFamily: 'Helvetica-Bold', color: '#374151', borderRightWidth: 1, borderColor: '#d1d5db' },
  cell: { padding: 5, borderRightWidth: 1, borderColor: '#d1d5db' },
  footer: { position: 'absolute', bottom: 24, left: 42, right: 42, fontSize: 8, color: '#9ca3af', textAlign: 'center', borderTopWidth: 1, borderColor: '#e5e7eb', paddingTop: 6 },
});

export interface ChecklistTest {
  name: string;
  unit: string;
  setup: string | null;
  procedure: string | null;
  mistakes: string | null;
}

interface Props {
  teamName: string;
  date: string;
  tests: ChecklistTest[];
  players: string[];
}

// A field-ready test day sheet: protocol summaries plus a blank result grid the coach
// fills in with a pen, then types into Test Day mode afterwards.
export function TestDayChecklistPDF({ teamName, date, tests, players }: Props) {
  const colWidth = `${72 / Math.max(tests.length, 1)}%`;
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.headerRow}>
          <View>
            <Text style={styles.brand}>ProTracker</Text>
            <Text style={styles.brandSub}>Test Day Checklist</Text>
          </View>
          <View>
            <Text style={styles.meta}>{teamName}</Text>
            <Text style={styles.meta}>{date}</Text>
          </View>
        </View>

        <Text style={styles.sectionTitle}>Results</Text>
        <View style={styles.tableHead}>
          <Text style={styles.nameCell}>Player</Text>
          {tests.map(t => (
            <Text key={t.name} style={[styles.th, { width: colWidth }]}>
              {t.name}{t.unit ? ` (${t.unit})` : ''}
            </Text>
          ))}
        </View>
        {players.map(p => (
          <View key={p} style={styles.tableRow} wrap={false}>
            <Text style={styles.nameCell}>{p}</Text>
            {tests.map(t => (
              <Text key={t.name} style={[styles.cell, { width: colWidth }]}> </Text>
            ))}
          </View>
        ))}

        <Text style={styles.sectionTitle}>Test Protocols</Text>
        {tests.map(t => (
          <View key={t.name} style={styles.testBlock} wrap={false}>
            <Text style={styles.testName}>{t.name}{t.unit ? ` — measured in ${t.unit}` : ''}</Text>
            {t.setup && (<>
              <Text style={styles.label}>Setup</Text>
              <Text style={styles.body}>{t.setup}</Text>
            </>)}
            {t.procedure && (<>
              <Text style={styles.label}>Procedure</Text>
              <Text style={styles.body}>{t.procedure}</Text>
            </>)}
            {t.mistakes && (<>
              <Text style={styles.label}>Avoid</Text>
              <Text style={styles.body}>{t.mistakes}</Text>
            </>)}
          </View>
        ))}

        <Text style={styles.footer} fixed>
          Generated by ProTracker — enter results in Team → Evidence → Test Day after the session.
        </Text>
      </Page>
    </Document>
  );
}
